export const actionList = [
  {
    name: 'Search',
    iconName: 'search',
    iconHTML: '<mat-icon class="material-icons-outlined">search</mat-icon>',
    iconCodePoint: 'e8b6',
    iconPath: 'assets/img/material-icons/action/search_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Home',
    iconName: 'home',
    iconHTML: '<mat-icon class="material-icons-outlined">home</mat-icon>',
    iconCodePoint: 'e88a',
    iconPath: 'assets/img/material-icons/action/home_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Settings',
    iconName: 'settings',
    iconHTML: '<mat-icon class="material-icons-outlined">settings</mat-icon>',
    iconCodePoint: 'e8b8',
    iconPath: 'assets/img/material-icons/action/settings_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Login',
    iconName: 'account_circle',
    iconHTML:
      '<mat-icon class="material-icons-outlined">account_circle</mat-icon>',
    iconCodePoint: 'e853',
    iconPath: 'assets/img/material-icons/action/account_circle_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Complete',
    iconName: 'done',
    iconHTML: '<mat-icon class="material-icons-outlined">done</mat-icon>',
    iconCodePoint: 'e876',
    iconPath: 'assets/img/material-icons/action/done_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Info',
    iconName: 'info',
    iconHTML: '<mat-icon class="material-icons-outlined">info</mat-icon>',
    iconCodePoint: 'e88e',
    iconPath: 'assets/img/material-icons/action/info_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Check Circle',
    iconName: 'check_circle',
    iconHTML:
      '<mat-icon class="material-icons-outlined">check_circle</mat-icon>',
    iconCodePoint: 'e86c',
    iconPath:
      'assets/img/material-icons/action/check_circle_outline_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Delete',
    iconName: 'delete',
    iconHTML: '<mat-icon class="material-icons-outlined">delete</mat-icon>',
    iconCodePoint: 'e872',
    iconPath: 'assets/img/material-icons/action/delete_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Logout',
    iconName: 'logout',
    iconHTML: '<mat-icon class="material-icons-outlined">logout</mat-icon>',
    iconCodePoint: 'e9ba',
    iconPath: 'assets/img/material-icons/action/logout_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Description',
    iconName: 'description',
    iconHTML:
      '<mat-icon class="material-icons-outlined">description</mat-icon>',
    iconCodePoint: 'e873',
    iconPath: 'assets/img/material-icons/action/description_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Lock',
    iconName: 'lock',
    iconHTML: '<mat-icon class="material-icons-outlined">lock</mat-icon>',
    iconCodePoint: 'e897',
    iconPath: 'assets/img/material-icons/action/lock_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Schedule',
    iconName: 'schedule',
    iconHTML: '<mat-icon class="material-icons-outlined">schedule</mat-icon>',
    iconCodePoint: 'e8b5',
    iconPath: 'assets/img/material-icons/action/schedule_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Global',
    iconName: 'language',
    iconHTML: '<mat-icon class="material-icons-outlined">language</mat-icon>',
    iconCodePoint: 'e894',
    iconPath: 'assets/img/material-icons/action/language_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Help',
    iconName: 'help_outline',
    iconHTML:
      '<mat-icon class="material-icons-outlined">help_outline</mat-icon>',
    iconCodePoint: 'e887',
    iconPath: 'assets/img/material-icons/action/help_outline_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Manage Account',
    iconName: 'manage_accounts',
    iconHTML:
      '<mat-icon class="material-icons-outlined">manage_accounts</mat-icon>',
    iconCodePoint: 'f02e',
    iconPath: 'assets/img/material-icons/action/manage_accounts_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Filter',
    iconName: 'filter_alt',
    iconHTML: '<mat-icon class="material-icons-outlined">filter_alt</mat-icon>',
    iconCodePoint: 'ef4f',
    iconPath: 'assets/img/material-icons/action/filter_alt_black_24dp.svg',
    isActive: false,
  },
  {
    name: 'Calendar Event',
    iconName: 'event',
    iconHTML: '<mat-icon class="material-icons-outlined">event</mat-icon>',
    iconCodePoint: 'e878',
    iconPath: 'assets/img/material-icons/action/event_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Verified',
    iconName: 'verified_user',
    iconHTML:
      '<mat-icon class="material-icons-outlined">verified_user</mat-icon>',
    iconCodePoint: 'e8e8',
    iconPath: 'assets/img/material-icons/action/verified_user_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Dashboard',
    iconName: 'dashboard',
    iconHTML: '<mat-icon class="material-icons-outlined">dashboard</mat-icon>',
    iconCodePoint: 'e871',
    iconPath: 'assets/img/material-icons/action/dashboard_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Calendar Today',
    iconName: 'calendar_today',
    iconHTML:
      '<mat-icon class="material-icons-outlined">calendar_today</mat-icon>',
    iconCodePoint: 'e935',
    iconPath: 'assets/img/material-icons/action/calendar_today_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'List View',
    iconName: 'format_list_bulleted',
    iconHTML:
      '<mat-icon class="material-icons-outlined">format_list_bulleted</mat-icon>',
    iconCodePoint: 'e241',
    iconPath: 'assets/img/material-icons/action/list_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Date Range',
    iconName: 'date_range',
    iconHTML: '<mat-icon class="material-icons-outlined">date_range</mat-icon>',
    iconCodePoint: 'e241',
    iconPath: 'assets/img/material-icons/action/date_range_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Remove',
    iconName: 'highlight_off',
    iconHTML:
      '<mat-icon class="material-icons-outlined">highlight_off</mat-icon>',
    iconCodePoint: 'e241',
    iconPath: 'assets/img/material-icons/action/highlight_off_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Paid',
    iconName: 'paid',
    iconHTML: '<mat-icon class="material-icons-outlined">paid</mat-icon>',
    iconCodePoint: 'f041',
    iconPath: 'assets/img/material-icons/action/paid_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Trending Up',
    iconName: 'trending_up',
    iconHTML:
      '<mat-icon class="material-icons-outlined">trending_up</mat-icon>',
    iconCodePoint: 'e8e5',
    iconPath: 'assets/img/material-icons/action/trending_up_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Trending Down',
    iconName: 'trending_down',
    iconHTML:
      '<mat-icon class="material-icons-outlined">trending_down</mat-icon>',
    iconCodePoint: 'e8e3',
    iconPath: 'assets/img/material-icons/action/trending_down_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Open in New',
    iconName: 'open_in_new',
    iconHTML:
      '<mat-icon class="material-icons-outlined">open_in_new</mat-icon>',
    iconCodePoint: 'e89e',
    iconPath: 'assets/img/material-icons/action/open_in_new_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Banking',
    iconName: 'account_balance',
    iconHTML:
      '<mat-icon class="material-icons-outlined">account_balance</mat-icon>',
    iconCodePoint: 'e84f',
    iconPath: 'assets/img/material-icons/action/account_balance_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'History',
    iconName: 'history',
    iconHTML: '<mat-icon class="material-icons-outlined">history</mat-icon>',
    iconCodePoint: 'e84f',
    iconPath: 'assets/img/material-icons/action/history_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Assignment',
    iconName: 'assignment',
    iconHTML: '<mat-icon class="material-icons-outlined">assignment</mat-icon>',
    iconCodePoint: 'e84f',
    iconPath: 'assets/img/material-icons/action/assignment_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Rating',
    iconName: 'star_rate',
    iconHTML: '<mat-icon class="material-icons-outlined">star_rate</mat-icon>',
    iconCodePoint: 'e84f',
    iconPath: 'assets/img/material-icons/action/star_rate_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Warning',
    iconName: 'report_problem',
    iconHTML:
      '<mat-icon class="material-icons-outlined">report_problem</mat-icon>',
    iconCodePoint: 'e84f',
    iconPath: 'assets/img/material-icons/action/report_problem_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Build',
    iconName: 'build',
    iconHTML: '<mat-icon class="material-icons-outlined">build</mat-icon>',
    iconCodePoint: 'e84f',
    iconPath: 'assets/img/material-icons/action/build_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Print',
    iconName: 'print',
    iconHTML: '<mat-icon class="material-icons-outlined">print</mat-icon>',
    iconCodePoint: 'e8ad',
    iconPath: 'assets/img/material-icons/action/print_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Refresh',
    iconName: 'autorenew',
    iconHTML: '<mat-icon class="material-icons-outlined">autorenew</mat-icon>',
    iconCodePoint: 'e863',
    iconPath: 'assets/img/material-icons/action/autorenew_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Charts One',
    iconName: 'analytics',
    iconHTML: '<mat-icon class="material-icons-outlined">analytics</mat-icon>',
    iconCodePoint: 'ef3e',
    iconPath: 'assets/img/material-icons/action/analytics_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Work',
    iconName: 'work_outline',
    iconHTML:
      '<mat-icon class="material-icons-outlined">work_outline</mat-icon>',
    iconCodePoint: 'e943',
    iconPath: 'assets/img/material-icons/action/work_outline_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Calendar Today',
    iconName: 'today',
    iconHTML: '<mat-icon class="material-icons-outlined">today</mat-icon>',
    iconCodePoint: 'e8df',
    iconPath: 'assets/img/material-icons/action/today_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Unlock',
    iconName: 'lock_open',
    iconHTML: '<mat-icon class="material-icons-outlined">lock_open</mat-icon>',
    iconCodePoint: 'e898',
    iconPath: 'assets/img/material-icons/action/lock_open_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Admin',
    iconName: 'admin_panel_settings',
    iconHTML:
      '<mat-icon class="material-icons-outlined">admin_panel_settings</mat-icon>',
    iconCodePoint: 'ef3d',
    iconPath:
      'assets/img/material-icons/action/admin_panel_settings_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Update',
    iconName: 'update',
    iconHTML: '<mat-icon class="material-icons-outlined">update</mat-icon>',
    iconCodePoint: 'e923',
    iconPath: 'assets/img/material-icons/action/update_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'List View',
    iconName: 'book',
    iconHTML: '<mat-icon class="material-icons-outlined">book</mat-icon>',
    iconCodePoint: 'e865',
    iconPath: 'assets/img/material-icons/action/book_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'List View',
    iconName: 'book',
    iconHTML: '<mat-icon class="material-icons-outlined">book</mat-icon>',
    iconCodePoint: 'e865',
    iconPath: 'assets/img/material-icons/action/book_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Add Doc',
    iconName: 'note_add',
    iconHTML: '<mat-icon class="material-icons-outlined">note_add</mat-icon>',
    iconCodePoint: 'e89c',
    iconPath: 'assets/img/material-icons/action/note_add_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Pending Action',
    iconName: 'pending_actions',
    iconHTML:
      '<mat-icon class="material-icons-outlined">pending_actions</mat-icon>',
    iconCodePoint: 'f1bb',
    iconPath: 'assets/img/material-icons/action/pending_actions_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Touch App',
    iconName: 'touch_app',
    iconHTML: '<mat-icon class="material-icons-outlined">touch_app</mat-icon>',
    iconCodePoint: 'e913',
    iconPath: 'assets/img/material-icons/action/touch_app_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Launch',
    iconName: 'launch',
    iconHTML: '<mat-icon class="material-icons-outlined">launch</mat-icon>',
    iconCodePoint: 'e895',
    iconPath: 'assets/img/material-icons/action/launch_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Charts Two',
    iconName: 'assessment',
    iconHTML: '<mat-icon class="material-icons-outlined">assessment</mat-icon>',
    iconCodePoint: 'e85c',
    iconPath: 'assets/img/material-icons/action/assessment_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Exit to App',
    iconName: 'exit_to_app',
    iconHTML:
      '<mat-icon class="material-icons-outlined">exit_to_app</mat-icon>',
    iconCodePoint: 'e879',
    iconPath: 'assets/img/material-icons/action/exit_to_app_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Zoom In',
    iconName: 'zoom_in',
    iconHTML: '<mat-icon class="material-icons-outlined">zoom_in</mat-icon>',
    iconCodePoint: 'e8ff',
    iconPath: 'assets/img/material-icons/action/zoom_in_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Open Full',
    iconName: 'open_in_full',
    iconHTML:
      '<mat-icon class="material-icons-outlined">open_in_full</mat-icon>',
    iconCodePoint: 'f1ce',
    iconPath: 'assets/img/material-icons/action/open_in_full_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Feedback',
    iconName: 'feedback',
    iconHTML: '<mat-icon class="material-icons-outlined">feedback</mat-icon>',
    iconCodePoint: 'e87f',
    iconPath: 'assets/img/material-icons/action/feedback_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Timeline',
    iconName: 'timeline',
    iconHTML: '<mat-icon class="material-icons-outlined">timeline</mat-icon>',
    iconCodePoint: 'e922',
    iconPath: 'assets/img/material-icons/action/timeline_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Add Task',
    iconName: 'add_task',
    iconHTML: '<mat-icon class="material-icons-outlined">add_task</mat-icon>',
    iconCodePoint: 'f23a',
    iconPath: 'assets/img/material-icons/action/add_task_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Contact Page',
    iconName: 'contact_page',
    iconHTML:
      '<mat-icon class="material-icons-outlined">contact_page</mat-icon>',
    iconCodePoint: 'f22e',
    iconPath: 'assets/img/material-icons/action/contact_page_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Get App',
    iconName: 'get_app',
    iconHTML: '<mat-icon class="material-icons-outlined">get_app</mat-icon>',
    iconCodePoint: 'e884',
    iconPath: 'assets/img/material-icons/action/get_app_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'App Settings',
    iconName: 'settings_applications',
    iconHTML:
      '<mat-icon class="material-icons-outlined">settings_applications</mat-icon>',
    iconCodePoint: 'e8b9',
    iconPath:
      'assets/img/material-icons/action/settings_applications_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Close Full Screen',
    iconName: 'close_fullscreen',
    iconHTML:
      '<mat-icon class="material-icons-outlined">close_fullscreen</mat-icon>',
    iconCodePoint: 'f1cf',
    iconPath:
      'assets/img/material-icons/action/close_fullscreen_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Sort',
    iconName: 'swap_vert',
    iconHTML: '<mat-icon class="material-icons-outlined">swap_vert</mat-icon>',
    iconCodePoint: 'e8d5',
    iconPath: 'assets/img/material-icons/action/swap_vert_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Info.',
    iconName: 'backup',
    iconHTML: '<mat-icon class="material-icons-outlined">backup</mat-icon>',
    iconCodePoint: 'e864',
    iconPath: 'assets/img/material-icons/action/backup_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'TOC',
    iconName: 'toc',
    iconHTML: '<mat-icon class="material-icons-outlined">toc</mat-icon>',
    iconCodePoint: 'e8de',
    iconPath: 'assets/img/material-icons/action/toc_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Zoom Out',
    iconName: 'zoom_out',
    iconHTML: '<mat-icon class="material-icons-outlined">zoom_out</mat-icon>',
    iconCodePoint: 'e900',
    iconPath: 'assets/img/material-icons/action/zoom_out_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Move',
    iconName: 'open_with',
    iconHTML: '<mat-icon class="material-icons-outlined">open_with</mat-icon>',
    iconCodePoint: 'e89f',
    iconPath: 'assets/img/material-icons/action/move_icon.svg',
    isActive: false,
  },
  {
    name: 'Bookmark',
    iconName: 'bookmark_add',
    iconHTML:
      '<mat-icon class="material-icons-outlined">bookmark_add</mat-icon>',
    iconCodePoint: 'e598',
    iconPath: 'assets/img/material-icons/action/bookmark_add_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Aspect Ratio',
    iconName: 'aspect_ratio',
    iconHTML:
      '<mat-icon class="material-icons-outlined">aspect_ratio</mat-icon>',
    iconCodePoint: 'e85b',
    iconPath: 'assets/img/material-icons/action/aspect_ratio_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Restore Settings',
    iconName: 'settings_backup_restore',
    iconHTML:
      '<mat-icon class="material-icons-outlined">settings_backup_restore</mat-icon>',
    iconCodePoint: 'e8ba',
    iconPath:
      'assets/img/material-icons/action/settings_backup_restore_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Set Alarm',
    iconName: 'alarm_on',
    iconHTML: '<mat-icon class="material-icons-outlined">alarm_on</mat-icon>',
    iconCodePoint: 'e858',
    iconPath: 'assets/img/material-icons/action/alarm_on_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Horiz Grid',
    iconName: 'view_column',
    iconHTML:
      '<mat-icon class="material-icons-outlined">view_column</mat-icon>',
    iconCodePoint: 'e8ec',
    iconPath: 'assets/img/material-icons/action/view_column_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Chart Three',
    iconName: 'addchart',
    iconHTML: '<mat-icon class="material-icons-outlined">addchart</mat-icon>',
    iconCodePoint: 'ef3c',
    iconPath: 'assets/img/material-icons/action/addchart_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Open in Browser',
    iconName: 'open_in_browser',
    iconHTML:
      '<mat-icon class="material-icons-outlined">open_in_browser</mat-icon>',
    iconCodePoint: 'e89d',
    iconPath: 'assets/img/material-icons/action/open_in_browser_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Unread Mail',
    iconName: 'mark_as_unread',
    iconHTML:
      '<mat-icon class="material-icons-outlined">mark_as_unread</mat-icon>',
    iconCodePoint: 'e9bc',
    iconPath: 'assets/img/material-icons/action/mark_as_unread_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Not Started',
    iconName: 'not_started',
    iconHTML:
      '<mat-icon class="material-icons-outlined">not_started</mat-icon>',
    iconCodePoint: 'f0d1',
    iconPath: 'assets/img/material-icons/action/not_started_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Bookmark Added',
    iconName: 'bookmark_added',
    iconHTML:
      '<mat-icon class="material-icons-outlined">bookmark_added</mat-icon>',
    iconCodePoint: 'e599',
    iconPath: 'assets/img/material-icons/action/bookmark_added_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Settings Input',
    iconName: 'settings_input_component',
    iconHTML:
      '<mat-icon class="material-icons-outlined">settings_input_component</mat-icon>',
    iconCodePoint: 'e8c0',
    iconPath:
      'assets/img/material-icons/action/settings_input_component_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'All Inbox',
    iconName: 'all_inbox',
    iconHTML: '<mat-icon class="material-icons-outlined">all_inbox</mat-icon>',
    iconCodePoint: 'e97f',
    iconPath: 'assets/img/material-icons/action/all_inbox_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Donut Large',
    iconName: 'donut_large',
    iconHTML:
      '<mat-icon class="material-icons-outlined">donut_large</mat-icon>',
    iconCodePoint: 'e917',
    iconPath: 'assets/img/material-icons/action/donut_large_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Donut Small',
    iconName: 'donut_small',
    iconHTML:
      '<mat-icon class="material-icons-outlined">donut_small</mat-icon>',
    iconCodePoint: 'e918',
    iconPath: 'assets/img/material-icons/action/donut_small_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Restore Trash',
    iconName: 'restore_from_trash',
    iconHTML:
      '<mat-icon class="material-icons-outlined">restore_from_trash</mat-icon>',
    iconCodePoint: 'e938',
    iconPath:
      'assets/img/material-icons/action/restore_from_trash_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Unread Mail',
    iconName: 'markunread_mailbox',
    iconHTML:
      '<mat-icon class="material-icons-outlined">markunread_mailbox</mat-icon>',
    iconCodePoint: 'e89b',
    iconPath:
      'assets/img/material-icons/action/markunread_mailbox_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Flip to Front',
    iconName: 'flip_to_front',
    iconHTML:
      '<mat-icon class="material-icons-outlined">flip_to_front</mat-icon>',
    iconCodePoint: 'e883',
    iconPath: 'assets/img/material-icons/action/flip_to_front_black_48dp.svg',
    isActive: false,
  },
  {
    name: 'Flip to Back',
    iconName: 'flip_to_back',
    iconHTML:
      '<mat-icon class="material-icons-outlined">flip_to_back</mat-icon>',
    iconCodePoint: 'e882',
    iconPath: 'assets/img/material-icons/action/flip_to_back_black_48dp.svg',
    isActive: false,
  },
];
